services:
  frontend:
    build:
      context: ./charts_frontend
      dockerfile: Dockerfile  
    ports:
      - '3000:3000'  
    stdin_open: true
    tty: true
    depends_on:
      - backend  

  backend:
    build:
      context: ./chart_backend
      dockerfile: Dockerfile  
    ports:
      - '8000:8000'  
    stdin_open: true
    tty: true

